### ISSUE TITLE
integer expression expected

### ISSUE THREAD

**Issue by Nitaro209** [MoBlockbuster/websiteinspector#4]
Hi,
super, tool :-)
Bei mir werden diese Fehler ausgeworfen:
./websiteinspector.sh: line 254: [: 0,136910: integer expression expected
./websiteinspector.sh: line 263: [: 0,136910: integer expression expected

**Comment by MoBlockbuster** [comment]
Hi Nitaro,

ist das Tool in der aktuellsten Version?
Führ mal ein websiteinspector -u aus.

**Comment by Nitaro209** [comment]
Hi !
ja, ist die aktuelle Version. 
webinspector -u sagt "I am up to date with version: 2021100203"
System ist Ubuntu Server 18.04 LTS

**Comment by MoBlockbuster** [comment]
Kannst du das Shellskript direkt von Git downloaden und auf dem Server ausführen? 

Schick mir mal ein Screenshot von der Stelle im Skript.

**Comment by Nitaro209** [comment]
Ich hatte das script via git clone auf den Server geholt, reicht das oder nochmal direkt runterladen ?
![error](https://user-images.githubusercontent.com/75988672/136035989-a8be715c-7fc7-4f1d-83d3-2e448a47443b.PNG)

**Comment by MoBlockbuster** [comment]
Ja das sieht nach einer alten Version aus.
Normalerweise müsste das Skript sich automatisch updaten.

Eventuell ist da was mit dem git client kaputt. 

Meine Empfehlung:

Sicher dir die config, Lösch den ganzen git Ordner und downloade das Paket nochmal. 

Danach solltest du die richtige Version haben.

**Comment by Nitaro209** [comment]
Es bleibt leider bei der Meldung. 
Wenn ich das als zip herunterlade kommt auch die Meldung, dann meckert sogar noch das er nicht up to date ist.
./websiteinspector.sh: line 254: [: 0,151063: integer expression expected
./websiteinspector.sh: line 263: [: 0,151063: integer expression expected
fatal: not a git repository (or any of the parent directories): .git

This file is managed by websiteinspector.sh.
Please do not change anything here!
HTTP problemes:
Updates are available for me! Start me with parameter -u. Date: 2021-10-05

**Comment by MoBlockbuster** [comment]
Ah okay.
Ich sehe das Problem.
Dein System ist auf deutsch oder?

**Comment by Nitaro209** [comment]
Ja, das ist richtig.
Welches Problem siehst du ?

**Comment by MoBlockbuster** [comment]
Zeile 248 und 249 stellen die Sprache des Systems vorübergehend auf Englisch um.

Kannst du mal die Sprache deines Systems auf Englisch umstellen und nochmal ausführen?

**Comment by Nitaro209** [comment]
Guten Morgen! 
Das ist ein Produktiv System da wollte ich ungern die Sprache ändern. Ich habe aber eine VM mit englischem System aufgesetzt und getestet. Da taucht der Fehler nicht auf. Ist es möglich auch die deutsche Sprache im Script einzubauen ?

**Comment by MoBlockbuster** [comment]
Das Problem ist folgender:

Der Curl-Output verwendet bei den floatzahlen im deutschen ein "," als Trenner und im Englischen ein "." .
In der Zeile 248 + 249 sieht man, dass ich dieses Problem so löse, dass ich die englischesprache vorrübergehend einsetze und danach den "." als Trenner erwarte.
Später stelle ich das System wieder auf die ursprüngliche Sprache zurück.

Ich habe das auch auf einem Ubuntu getestet und es funktionierte.

Kannst du das Skript mal auf einem anderen Ubuntu 18 und auf einem Ubuntu 20 testen?
Was sind die Ergebnisse?


Als vorrübergehende Lösung kannst du folgendes machen:

In Zeile 251 + 252 ersetzt du den "." mit einem ",".

Danach hast du es >erstmal< gelöst.

**Comment by Nitaro209** [comment]
Guten Morgen!
Auf dem 20.04. in deutsch tritt der gleiche Fehler auf, 20.04 english tritt er nicht auf.
Für ein anderes 18.04 muss ich erstmal eine VM aufsetzen. Vielleicht bringt es was nur das english language pack zu installieren.
Edit: Auf einem deutschen 18.04. auf meiner VM tritt der Fehler nicht auf. 

Interessant finde ich auf dem "betroffenen" System, wenn ich den websiteinspector mit bash -x ausführe, dann gibt er bei dem language wechsel folgendes aus:
`++ echo en_US.UTF-8
+ ORILANG=en_US.UTF-8
+ export LANG=en_US.UTF-8
+ LANG=en_US.UTF-8
++ /usr/bin/curl -L --user-agent websiteinspector --write-out '%{time_total}\n' https://xxx.xxx.de --silent --output /dev/null --max-time 8
+ TIMERAW=0,154777
++ awk -F . '{ print $1 }'
++ echo 0,154777
+ TIME=0,154777
++ echo 0,154777
++ awk -F . '{ print $2 }'
+ TIME2=
+ TIMEFINAL=0,154777.
+ '[' 0,154777 -lt 3 ']'
websiteinspector.sh: line 254: [: 0,154777: integer expression expected
+ '[' 0,154777 -ge 3 ']'
websiteinspector.sh: line 263: [: 0,154777: integer expression expected
`
Also beim echo der Systemsprache sagt er es sei en_US.UTF-8, gibt aber , statt . aus.
Wenn ich das echo aber manuell auf der console ausgebe, sagt er er habe de_DE.UTF-8.
Das verstehe ich noch nicht.

**Comment by MoBlockbuster** [comment]
Führ mal die curl Zeile manuell aus. Stelle danach die Sprachen um.

Wenn auf Englisch trotzdem ein "," kommt, dann stimmt was nicht. 

Eventuell schauen ob englisch unterstützt wird. 

In meinem test mit einem ubuntu20 hat es sofort funktioniert

**Comment by Nitaro209** [comment]
Ich gebe mal auf an dieser Stelle, offensichtlich liegt es an dem System. Da müssen wir beide nicht noch mehr Zeit für Opfern. Ich workarounde das mit Komma. Besten Dank für deine Hilfe !

**Comment by MoBlockbuster** [comment]
Gerne doch :)
